-- MySQL Workbench Synchronization
-- Generated: 2019-04-27 16:40
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: thayl

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `myLinks` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `myLinks`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `contra` BLOB NOT NULL,
  `estado` SMALLINT(5) NOT NULL DEFAULT 0,
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `myLinks`.`link` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `icono` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(200) NOT NULL,
  `url` LONGTEXT NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_link_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_link_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `myLinks`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
